# Generated by Django 3.0.7 on 2020-09-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
